version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    depends_on:
      db:
        condition: service_healthy
    command: >
      /bin/sh -c 'alembic upgrade head && gunicorn src.main:app -c /app/src/gunicorn.conf.py'
    tty: true

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - ./_var:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE}"
        ]
      interval: 5s
      retries: 3
